# Site wide configuration

title:            Lynn-Group-JNU
locale:           en_US
url:			  https://lynngroup.github.io

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : G-Q4QNGTVVMY
    anonymize_ip: false # default
# Google Analytics
#google_analytics: G-Q4QNGTVVMY

# Site owner
owner:
  name: Lynn-Group-JNU
  avatar: shail.jpg
  bio: "Bioinformatics Research Lab"
  email: #shailniboriya@gmail.com
#  disqus-shortname: https-timotheenivalis-github-io
  twitter: s#hailniboriya
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Lynn-Group-JNU
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr:
  codepen: #username

include: [".htaccess", "_pages"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      comments: true
      read_time: true
      share: true
      author_profile: true
      related: false

# Comments
comments:
  provider:
  disqus:
    shortname: isugifwiki
